<#
.SYNOPSIS
Initializes the HRP 3-tier pipeline config for one or more CLI Coding Agents.

.DESCRIPTION
Generates wrapper files at the repo root so various CLI Coding Agents can
auto-load HRP rules, agents, skills and commands. Source of truth is
`.ai-pipeline/` (rules, skills, agents, templates). Bootstrap files are
derivable; never edit them directly.

.PARAMETER ProjectPath
Path to the HRP repo root. Defaults to current directory.

.PARAMETER Agent
Which Agent wrapper(s) to generate. Accepts:
- cursor           → .cursor/rules/hrp.mdc
- antigravity      → GEMINI.md
- claude-code      → CLAUDE.md
- vscode-copilot   → .github/copilot-instructions.md
- opencode         → OPENCODE.md
- all              → every wrapper above

.EXAMPLE
pwsh .ai-pipeline/scripts/init-project.ps1 -Agent all

.EXAMPLE
pwsh .ai-pipeline/scripts/init-project.ps1 -Agent antigravity -Agent claude-code

.NOTES
Run from anywhere. Idempotent: re-running overwrites generated wrappers
without touching .ai-pipeline/ source.
#>
[CmdletBinding()]
param(
    [string]$ProjectPath = $PWD.Path,
    [string]$Agent = "all"
)

$ErrorActionPreference = "Stop"

$colors = @{
    OK    = "Green"
    INFO  = "Cyan"
    WARN  = "Yellow"
    FAIL  = "Red"
    TITLE = "Magenta"
}

function Write-Utf8 {
    param([string]$Path, [string]$Content)
    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path -LiteralPath $dir -PathType Container)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
}

function Write-Status {
    param([string]$Level, [string]$Message)
    Write-Host "[$Level] $Message" -ForegroundColor $colors[$Level]
}

function Get-RelPath {
    param([string]$From, [string]$To)
    $fromAbs = (Resolve-Path -LiteralPath $From).Path.TrimEnd('\','/').Replace('/','\')
    $toAbs   = (Resolve-Path -LiteralPath $To).Path.TrimEnd('\','/').Replace('/','\')
    $fromParts = $fromAbs -split '\\'
    $toParts   = $toAbs   -split '\\'
    $i = 0
    while ($i -lt $fromParts.Length -and $i -lt $toParts.Length -and $fromParts[$i] -eq $toParts[$i]) {
        $i++
    }
    $up = if ($fromParts.Length - $i - 1 -gt 0) { @('..') * ($fromParts.Length - $i - 1) } else { @() }
    $down = if ($i -lt $toParts.Length) { $toParts[$i..($toParts.Length - 1)] } else { @() }
    $parts = @() + $up + $down
    if ($parts.Count -eq 0) { return '.' }
    return ($parts -join '/')
}

try {
    if ([string]::IsNullOrWhiteSpace($Agent)) {
        $Agent = "all"
    }
    $parts = $Agent -split '[,\s]+' | Where-Object { $_ -ne '' }
    $lower = $parts | ForEach-Object { $_.ToLower() }

    if ($lower -contains "all") {
        $targets = @("cursor", "antigravity", "claude-code", "vscode-copilot", "opencode")
    } else {
        $targets = $lower
    }

    $allowed = @("cursor", "antigravity", "claude-code", "vscode-copilot", "opencode")
    foreach ($t in $targets) {
        if ($allowed -notcontains $t) {
            Write-Status FAIL "Unknown agent '$t'. Allowed: $($allowed -join ', ')"
            exit 2
        }
    }

    $resolvedProject = (Resolve-Path -LiteralPath $ProjectPath).Path
    Write-Status TITLE "HRP Pipeline Bootstrap"
    Write-Status INFO "  Project : $resolvedProject"
    Write-Status INFO "  Agents  : $($targets -join ', ')"

    $pipelineDir = Join-Path $resolvedProject ".ai-pipeline"
    if (-not (Test-Path -LiteralPath $pipelineDir -PathType Container)) {
        Write-Status FAIL "Missing .ai-pipeline at $pipelineDir. Cannot bootstrap."
        exit 2
    }

    # -------------------------------------------------- Cursor
    function Write-Cursor {
        param([string]$Root)
        $dir = Join-Path $Root ".cursor\rules"
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        $rel = Get-RelPath -From $dir -To (Join-Path $Root ".ai-pipeline")
        $content = @"
# Auto-generated by .ai-pipeline/scripts/init-project.ps1 - DO NOT EDIT.
# Source of truth: $($rel.Replace('\\','/'))

description: HRP 3-tier pipeline rules. Loaded automatically when working in this repo.

# When to apply
These rules apply to every HRP task. Skip only if user explicitly opts out.

# Roles
- Tier 1 (Planner): see $($rel)/agents/planner.md
- Tier 2 (Engineer): see $($rel)/agents/engineer.md
- Tier 3 (Auditor): see $($rel)/agents/auditor.md
- Cross-Compat mapping: $($rel)/agents/CROSS-COMPAT.md

# Role Manifests (Cursor-format, include all)
- $($rel)/tier1.md
- $($rel)/tier2.md
- $($rel)/tier3.md

# Hard Rules (BẮT BUỘC)
1. Tier 1 KHÔNG viết code thay Tier 2.
2. Tier 2 KHÔNG tự audit chính mình.
3. Tier 3 KHÔNG tự fix hay đổi contract.
4. Mọi claim phải có evidence thật (command + exit code + output).
5. Không sửa wrapper file này; sửa $($rel)/rules/ sau đó re-run init.

# Skill Index
Read $($rel)/SKILL-ECOSYSTEM.md for Decision Matrix và tier → skill mapping.

# Pipeline Workflow
Read $($rel)/PIPELINE-GUIDE.md cho commands /plan, /code, /audit, /resolve.
"@
        $out = Join-Path $dir "hrp.mdc"
        Write-Utf8 -Path $out -Content $content
        Write-Status OK "Cursor  → $out"
    }

    # -------------------------------------------------- Antigravity / Gemini CLI
    function Write-Antigravity {
        param([string]$Root)
        $rel = Get-RelPath -From $Root -To (Join-Path $Root ".ai-pipeline")
        $content = @"
# Auto-generated by .ai-pipeline/scripts/init-project.ps1 - DO NOT EDIT.
# Source of truth: $($rel.Replace('\\','/'))

You operate inside the HRP 3-tier pipeline. The repo's source of truth
lives at $($rel). Use this file only as an index; do NOT inline its contents
for execution.

## Roles
| Tier | Role | Manifest |
|---|---|---|
| 1 | Planner | $($rel)/agents/planner.md |
| 2 | Engineer | $($rel)/agents/engineer.md |
| 3 | Auditor | $($rel)/agents/auditor.md |
| - | Cross-Compat | $($rel)/agents/CROSS-COMPAT.md |

## Tier Role Manifests (full prompts)
- $($rel)/tier1.md — Tier 1 role, ranh giới, contract duy nhất.
- $($rel)/tier2.md — Tier 2 role, ranh giới, preflight, HANDOFF output.
- $($rel)/tier3.md — Tier 3 role, ranh giới, audit mode, AUDIT output.

## Hard Rules
1. Tier 1 owns TASK.md contracts. NEVER edit source code in this tier.
2. Tier 2 owns HANDOFF.md. NEVER self-audit.
3. Tier 3 owns AUDIT.md. NEVER fix or modify contract.
4. Evidence must be real (command + exit code + output). Mock evidence = block.
5. Wrapper files (this one, CLAUDE.md, .cursor/rules/*.mdc,
   .github/copilot-instructions.md) are derived. To change behavior, edit
   $($rel)/* and re-run init.

## Skill Map
$($rel)/SKILL-ECOSYSTEM.md

## Commands (Gemini CLI mapping)
- /plan [slug]     → Tier 1
- /code [slug]     → Tier 2
- /audit [slug]    → Tier 3
- /resolve [slug]  → Tier 1 (close round)

If no slug is passed, the command must read STATUS in docs/tasks/*/TASK.md
to find the next task automatically.
"@
        $out = Join-Path $Root "GEMINI.md"
        Write-Utf8 -Path $out -Content $content
        Write-Status OK "Antigravity → $out"
    }

    # -------------------------------------------------- Claude Code
    function Write-ClaudeCode {
        param([string]$Root)
        $rel = Get-RelPath -From $Root -To (Join-Path $Root ".ai-pipeline")
        $content = @"
# Auto-generated by .ai-pipeline/scripts/init-project.ps1 - DO NOT EDIT.
# Source of truth: $($rel.Replace('\\','/'))

You operate inside the HRP 3-tier pipeline. Source of truth: $($rel).

## Iron Rules
1. Tier 1 (Planner): write TASK.md contracts only. Never edit code.
2. Tier 2 (Engineer): execute TASK contracts → write HANDOFF.md. Never self-audit.
3. Tier 3 (Auditor): read TASK + HANDOFF, audit independently → write AUDIT.md.
   Never fix code or change contract.
4. Evidence must be REAL (command + exit code + output). Mock evidence = block.
5. Do NOT edit this file. Edit $($rel)/* and re-run init.

## Tier Manifests
- $($rel)/agents/planner.md
- $($rel)/agents/engineer.md
- $($rel)/agents/auditor.md
- $($rel)/agents/CROSS-COMPAT.md
- $($rel)/tier1.md
- $($rel)/tier2.md
- $($rel)/tier3.md

## Skill Map
$($rel)/SKILL-ECOSYSTEM.md
"@
        $out = Join-Path $Root "CLAUDE.md"
        Write-Utf8 -Path $out -Content $content
        Write-Status OK "Claude Code → $out"
    }

    # -------------------------------------------------- VSCode Copilot
    function Write-VSCodeCopilot {
        param([string]$Root)
        $dir = Join-Path $Root ".github"
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        $rel = Get-RelPath -From $dir -To (Join-Path $Root ".ai-pipeline")
        $content = @"
# Auto-generated by .ai-pipeline/scripts/init-project.ps1 - DO NOT EDIT.
# Source of truth: $($rel.Replace('\\','/'))

## Repository Instructions
This repo runs the HRP 3-tier pipeline. Source of truth at $($rel).

## Roles
| Tier | Role | Manifest |
|---|---|---|
| 1 | Planner | $($rel)/agents/planner.md |
| 2 | Engineer | $($rel)/agents/engineer.md |
| 3 | Auditor | $($rel)/agents/auditor.md |
| - | Tier 1 prompt | $($rel)/tier1.md |
| - | Tier 2 prompt | $($rel)/tier2.md |
| - | Tier 3 prompt | $($rel)/tier3.md |

## Iron Rules
1. Tier 1: contracts only. No code.
2. Tier 2: no self-audit.
3. Tier 3: no fix, no contract change.
4. Evidence must be real (command + exit code + output snippet).
5. Do NOT edit this file; edit $($rel)/* and re-run init.

## Skill Map
$($rel)/SKILL-ECOSYSTEM.md
"@
        $out = Join-Path $dir "copilot-instructions.md"
        Write-Utf8 -Path $out -Content $content
        Write-Status OK "VSCode Copilot → $out"
    }

    # -------------------------------------------------- OpenCode
    function Write-OpenCode {
        param([string]$Root)
        $rel = Get-RelPath -From $Root -To (Join-Path $Root ".ai-pipeline")
        $content = @"
# Auto-generated by .ai-pipeline/scripts/init-project.ps1 - DO NOT EDIT.
# Source of truth: $($rel.Replace('\\','/'))

This repo follows the HRP 3-tier pipeline (Planner → Engineer → Auditor).
Source of truth: $($rel).

Roles: see $($rel)/agents/{planner,engineer,auditor}.md
Role prompts (full): see $($rel)/tier{1,2,3}.md
Hard rules:
- Tier 1: contracts only.
- Tier 2: no self-audit; evidence must be real.
- Tier 3: no fix, no contract change; tự reproduce verify commands.
Skills: see $($rel)/SKILL-ECOSYSTEM.md
Workflow: see $($rel)/PIPELINE-GUIDE.md
"@
        $out = Join-Path $Root "OPENCODE.md"
        Write-Utf8 -Path $out -Content $content
        Write-Status OK "OpenCode → $out"
    }

    # Dispatch
    foreach ($t in $targets) {
        switch ($t) {
            "cursor"        { Write-Cursor -Root $resolvedProject }
            "antigravity"   { Write-Antigravity -Root $resolvedProject }
            "claude-code"   { Write-ClaudeCode -Root $resolvedProject }
            "vscode-copilot"{ Write-VSCodeCopilot -Root $resolvedProject }
            "opencode"      { Write-OpenCode -Root $resolvedProject }
        }
    }

    Write-Status TITLE "Done."
    Write-Status INFO "Source of truth (.ai-pipeline/) is intact; only root wrappers generated."
    exit 0
}
catch {
    Write-Status FAIL "Init failed: $($_.Exception.Message)"
    exit 2
}
